### ISSUE TITLE
Current state progress

### ISSUE THREAD

**Issue by NidhiHemanth** [SubconsciousCompute/windows-snapshot#15]
[Operating System Classes](https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/operating-system-classes):

~- [ ] [COM](https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/operating-system-classes#com)~ *not needed*
- [x] [Desktop](https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/operating-system-classes#desktop)
- [x] [Drivers](https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/operating-system-classes#drivers)
- [x] [Event log](https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/operating-system-classes#windows-event-log)
- [x] [File system](https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/operating-system-classes#file-system)
- [x] [Job objects](https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/operating-system-classes#job-objects)
- [x] [Memory and page files](https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/operating-system-classes#memory-and-page-files)
- [x] [Multimedia audio or visual](https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/operating-system-classes#multimedia-audio-or-visual)
- [x] [Networking](https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/operating-system-classes#networking)

~- [ ] [Operating system events](https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/operating-system-classes#operating-system-events)~ *not needed*
- [x] [Operating system settings](https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/operating-system-classes#operating-system-settings)
- [x] [Processes](https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/operating-system-classes#processes)
- [x] [Registry](https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/operating-system-classes#registry)
- [x] [Scheduler jobs](https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/operating-system-classes#scheduler-jobs)
- [x] [Security](https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/operating-system-classes#security)
- [x] [Services](https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/operating-system-classes#services)
- [x] [Shares](https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/operating-system-classes#shares)
- [x] [Start menu](https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/operating-system-classes#start-menu)
- [x] [Storage](https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/operating-system-classes#storage)
- [x] [Users](https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/operating-system-classes#users)

~- [ ] [Windows product activation](https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/operating-system-classes#windows-product-activation)~ *replaced with:*  
- [x] [Software License Provider](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/sppwmi/software-license-provider-?redirectedfrom=MSDN)

**Comment by sn99** [comment]
Followed up in #15

**Comment by sn99** [comment]
@NidhiHemanth Can we have one last check?

**Comment by NidhiHemanth** [comment]
@sn99 yep, on it.

**Comment by NidhiHemanth** [comment]
Closes #26

**Comment by sn99** [comment]
10K+ lines xD
